apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: local-storage
          mountPath: /data
  volumes:
    - name: local-storage
      persistentVolumeClaim:
        claimName: demo-pvc # This targets your exact PVCX
